//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HeroApp
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DataBaseFirstEntities : DbContext
    {
        public DataBaseFirstEntities()
            : base("name=DataBaseFirstEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Hero> Hero { get; set; }
        public virtual DbSet<RatingHistorial> RatingHistorial { get; set; }
        public virtual DbSet<ExceptionLog> ExceptionLog { get; set; }
    }
}
